### ISSUE TITLE
Nuevo mapa de la DGE.

### ISSUE THREAD

**Issue by carranco-sga** [mariorz/covid19-mx-time-series#1]
Hola, @mariorz:

Abro el issue para informarte de un par de cosas (buenas) que acabo de encontrar:

1) Hay un archivo oficial con datos abiertos de la SSa!: https://www.gob.mx/salud/documentos/datos-abiertos-152127

2) Hay un nuevo mapa de la DGE, con tasas de incidencia: https://ncov.sinave.gob.mx/mapatasas.aspx

Saludos,
Gabriel.

**Comment by mariorz** [comment]
Hola @carranco-sga, gracias por el aviso, ya estoy explorando este CSV. Igual interesante lo del mapa, parece agregaron campos al mismo json para los valores del nuevo, creo va a ser fácil empezar a recolectarlos
