### ISSUE TITLE
edn file

### ISSUE THREAD

**Issue by lorenzo-gabrielli** [mariorz/covid19-mx-time-series#3]
Dear,

Is it possible to clarify the meaning of the cells in the states.edn file?
e.g. ['1', 'Aguascalientes', '1353758.409', '01', '0', '0', '0', '0'], 
      ['2', 'Baja California', '3682063.4', '02', '0', '0', '0', '0']
The first should be the state code, the second the name, the third should be the number of residents, then again the state code.
But it is not clear to me the meaning of the other 4 cells. I suppose the number of cases/deaths etc, but is not clear the order.

Is it possible to upload the data in a different format, for example, JSON?

Best

**Comment by mariorz** [comment]
Hi, sorry for taking so long to respond.
states.edn is really a legacy data file from when we used to extract daily data from a map at the Secretaría de Salud website
It should not really be used for anything as all the data is converted to the csv files as documented on the README.
Closing this issue, but let me know if you have other questions.
